linters-settings:
  govet:
    disable:
      - shadow # default value recommended by golangci
      - composites

  gomoddirectives:
    replace-local: false
    replace-allow-list:
      - "github.com/osbuild/images"

linters:
  enable:
    - gosec
    - gomoddirectives

run:
  build-tags:
    - integration
  timeout: 5m

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
  exclude-rules:
    - path: ^(osbuild-composer/)?cmd/osbuild-worker-executor/.*_test\.go$
      linters: ["gosec"]
