# https://packit.dev/docs/configuration/

specfile_path: osbuild-composer.spec

synced_files:
    - osbuild-composer.spec
    - .packit.yaml

copy_upstream_release_description: true

upstream_tag_template: v{version}

srpm_build_deps: []
actions:
  get-current-version: bash -c "git describe --tags --abbrev=0 | sed 's|v||'"
  post-upstream-clone: "./tools/rpm_spec_add_provides_bundle.sh"

jobs:
- job: bodhi_update
  trigger: commit
  dist_git_branches:
    - fedora-branched # rawhide updates are created automatically
- job: koji_build
  trigger: commit
  dist_git_branches:
    - fedora-all
- job: propose_downstream
  trigger: release
  dist_git_branches:
    - fedora-all
- job: copr_build
  trigger: pull_request
  targets: &build_targets
    - centos-stream-8-aarch64
    - centos-stream-8-x86_64
    - centos-stream-9-aarch64
    - centos-stream-9-x86_64
    - fedora-all-aarch64
    - fedora-all-s390x
    - fedora-all-ppc64le
    - fedora-all
    - rhel-8-aarch64
    - rhel-8-x86_64
    - rhel-9-aarch64
    - rhel-9-x86_64
- job: copr_build
  trigger: commit
  branch: main
  owner: "@osbuild" # copr repo namespace
  project: osbuild-composer  # copr repo name so you can consume the builds
  targets: *build_targets
