# https://packit.dev/docs/configuration/

specfile_path: osbuild-composer.spec

files_to_sync:
    - osbuild-composer.spec
    - .packit.yaml

upstream_package_name: osbuild-composer
downstream_package_name: osbuild-composer

copy_upstream_release_description: true

upstream_tag_template: v{version}

srpm_build_deps: []
actions:
  get-current-version: bash -c "git describe --tags --abbrev=0 | sed 's|v||'"
  post-upstream-clone: "./tools/rpm_spec_add_provides_bundle.sh"

jobs:
- job: bodhi_update
  trigger: commit
  dist_git_branches:
    - fedora-branched # rawhide updates are created automatically
- job: koji_build
  trigger: commit
  metadata:
    dist_git_branches:
      - fedora-all
- job: propose_downstream
  trigger: release
  metadata:
    dist_git_branches:
      - fedora-all
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - centos-stream-9-aarch64
    - centos-stream-9-x86_64
