version: '2.4'
services:
  composer:
    image: local/osbuild-composer
    build:
      context: ..
      dockerfile: ./distribution/Dockerfile-ubi
    volumes:
      - ${CONTAINER_CONFIG_DIR}/:/etc/osbuild-composer
    networks:
      net:
        ipv4_address: 172.30.0.10
  worker:
    image: local/osbuild-worker
    build:
      context: ..
      dockerfile: ./distribution/Dockerfile-worker
    # override the entrypoint to specify composer hostname and port
    entrypoint: ["/usr/libexec/osbuild-composer/osbuild-worker" "https://composer:8700"]
    volumes:
      - ${CONTAINER_CONFIG_DIR}/:/etc/osbuild-composer
    environment:
      - CACHE_DIRECTORY=/var/cache/osbuild-worker
    privileged: true
    cap_add:
      - MKNOD
      - SYS_ADMIN
      - NET_ADMIN
    networks:
      net:
        ipv4_address: 172.30.0.20
    depends_on:
      - "composer"

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
