FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

RUN curl --location --output /etc/yum.repos.d/hashicorp.repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
RUN microdnf install -y packer openssh-clients unzip python3 python3-pip

RUN pip3 install ansible
RUN ansible-galaxy collection install ansible.posix

RUN curl https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip -o /tmp/awscli.zip
RUN unzip /tmp/awscli.zip
RUN aws/install

# copy in entire workspace
COPY . /osbuild-composer
