{
 "title": "Image Builder Composer",
 "time": { "from": "now-28d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "5m,30m,1h,6h,12h,1d,3d,7d,14d,28d"
   },
   { "name": "stability_slo", "query": "0.95" },
   { "name": "stability_error_budget", "query": "0.05" }
  ]
 },
 "panels": [
  { "title": "Compose Stability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Compose Success Rate",
   "type": "stat",
   "description": "The percentage of successful compose requests for the selected time range and interval",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(total_successful_compose_requests[$__range]))/sum(increase(total_compose_requests[$__range]))"
    }
   ]
  },
  {
   "title": "Compose Requests",
   "type": "stat",
   "description": "The number of total compose requests for the selected interval",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(total_compose_requests[$__range]))"
    }
   ]
  },
  {
   "title": "Compose Errors",
   "type": "timeseries",
   "description": "The number of compose errors (as a percentage) over time for the selected time range and interval",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(increase(total_successful_compose_requests[$__range]))/sum(increase(total_compose_requests[$__range]))"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "stat",
   "description": "How long will it take to consume all our budget if our error consumption remains at the current rate for the selected interval.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "28 * 24 * $stability_error_budget / ((1 - sum(rate(total_successful_compose_requests[$__range])) by (job) / sum(rate(total_compose_requests[$__range])) by (job)))"
    }
   ]
  },
  {
   "title": "Error Budget Consumed",
   "type": "timeseries",
   "description": "The percentage of error budget consumed for the selected time range and interval. ",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((sum(increase(total_successful_compose_requests[28d]))/sum(increase(total_compose_requests[28d]))) - $stability_slo)/ (1 - $stability_slo)",
     "legendFormat": "errorbudget"
    }
   ]
  }
 ]
}