{
 "title": "Image Builder Worker",
 "time": { "from": "now-28d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "5m,30m,1h,6h,12h,1d,3d,7d" },
   { "name": "stability_slo", "query": "0.95" },
   { "name": "latency_slo", "query": "0.95" }
  ]
 },
 "panels": [
  { "title": "Build Job Success Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build Job Success Rate",
   "type": "stat",
   "description": "The percentage of successful osbuild jobs for the selected time range",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (\n  (\n    sum(increase(image_builder_worker_total_jobs{type=~\"osbuild:.*\", status=\"5xx\"}[$__range]))\n    /\n    sum(increase(image_builder_worker_total_jobs{type=~\"osbuild:.*\", status!=\"4xx\"}[$__range])) \n  ) OR on() vector(0) # set a fallback if the query result is empty\n)"
    }
   ]
  },
  {
   "title": "Build Job Throughput Rate",
   "type": "timeseries",
   "description": "The throughput rate of osbuild job errors and non-errors over time for the selected time range",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(rate(image_builder_worker_total_jobs{type=~\"osbuild:.*\", status!=\"4xx\"}[$interval])) OR on() vector(0))\n- \n(sum(rate(image_builder_worker_total_jobs{type=~\"osbuild:.*\", status=\"5xx\"}[$interval])) OR on() vector(0))",
     "legendFormat": "success/sec"
    },
    {
     "expr": "(sum(rate(image_builder_worker_total_jobs{type=~\"osbuild:.*\", status=\"5xx\"}[$interval])) OR on() vector(0))",
     "legendFormat": "errors/sec"
    }
   ]
  },
  {
   "title": "Build Job Error Rate",
   "type": "timeseries",
   "description": "The number of osbuild job errors (as a percentage) over time for the selected time range",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(image_builder_worker_total_jobs{type=~\"osbuild:.*\", status=\"5xx\"}[$interval]))\n  /\n  sum(rate(image_builder_worker_total_jobs{type=~\"osbuild:.*\", status!=\"4xx\"}[$interval]))\n)\nOR on() vector(0) # set fallback incase the above query result is empty"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "stat",
   "description": "How long will it take to consume all our budget if our error consumption remains at the current rate for the selected date range.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "28 * 24 * (1 - $stability_slo)\n/ \n(\n  (\n    sum(rate(image_builder_worker_total_jobs{type=~\"osbuild:.*\", status=\"5xx\"}[28d]))\n    / \n    sum(rate(image_builder_worker_total_jobs{type=~\"osbuild:.*\", status!=\"4xx\"}[28d]))\n  ) OR on() vector(0.01) # set fallback incase the above query result is empty\n)"
    }
   ]
  },
  {
   "title": "Error Budget Consumed",
   "type": "timeseries",
   "description": "The percentage of error budget consumed for the selected time range. ",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  (\n    1 - $stability_slo - (\n      (\n        sum(increase(image_builder_worker_total_jobs{type=~\"osbuild:.*\", status=\"5xx\"}[28d]))\n        /\n        sum(increase(image_builder_worker_total_jobs{type=~\"osbuild:.*\", status!=\"4xx\"}[28d]))\n      ) OR on() vector(0) # set fallback for empty query result\n    ) \n  ) \n)\n/ \n(1 - $stability_slo)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  { "title": "Build Job Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Build Job Duration",
   "type": "stat",
   "description": "The duration of 95% of osbuild jobs",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(image_builder_worker_job_duration_seconds_bucket{type=~\"osbuild:.*\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Build Job Duration",
   "type": "timeseries",
   "description": "The request Duration for osbuild jobs over the selected date range",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(image_builder_worker_job_duration_seconds_bucket{type=~\"osbuild:.*\"}[$interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(image_builder_worker_job_duration_seconds_bucket{type=~\"osbuild:.*\"}[$interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(image_builder_worker_job_duration_seconds_bucket{type=~\"osbuild:.*\"}[$interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Slow Request Rate",
   "type": "timeseries",
   "description": "Percent of requests exceeding Duration allowed by SLO",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(rate(image_builder_worker_job_duration_seconds_bucket{le=\"1536\",type=~\"osbuild:.*\"}[$interval]))/sum(rate(image_builder_worker_job_duration_seconds_count{type=~\"osbuild:.*\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "stat",
   "description": "How long will it take to consume all our budget if our error consumption remains at the current rate for the selected date range.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "28 * 24 * (1 - $latency_slo) \n/ \n( \n  1.001 - ( \n    (\n      sum(rate(image_builder_worker_job_duration_seconds_bucket{le=\"1536\",type=~\"osbuild:.*\"}[$__range]))\n      /\n      sum(rate(image_builder_worker_job_duration_seconds_count{type=~\"osbuild:.*\"}[$__range]))\n    )  OR on() vector(1) # set fallback incase the above query result is empty\n  )\n)"
    }
   ]
  },
  {
   "title": "Error Budget Consumed",
   "type": "timeseries",
   "description": "The percentage of error budget consumed for the selected time range. ",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  (\n    (\n      sum(increase(image_builder_worker_job_duration_seconds_bucket{le=\"1536\",type=~\"osbuild:.*\"}[28d]))\n      /\n      sum(increase(image_builder_worker_job_duration_seconds_count{type=~\"osbuild:.*\"}[28d])) \n    ) OR on() vector(1)  \n  ) - $latency_slo\n)\n/\n(1 - $latency_slo)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  { "title": "Depsolve Job Success Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Depsolve Job Success Rate",
   "type": "stat",
   "description": "The percentage of successful depsolve jobs for the selected time range",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (\n  (\n    sum(increase(image_builder_worker_total_jobs{type=\"depsolve\", status=\"5xx\"}[$__range]))\n    /\n    sum(increase(image_builder_worker_total_jobs{type=\"depsolve\", status!=\"4xx\"}[$__range])) \n  ) OR on() vector(0) # set a fallback if the query result is empty\n)"
    }
   ]
  },
  {
   "title": "Depsolve Job Throughput Rate",
   "type": "timeseries",
   "description": "The throughput rate of depsolve job errors and non-errors over time for the selected time range",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(rate(image_builder_worker_total_jobs{type=\"depsolve\", status!=\"4xx\"}[$interval])) OR on() vector(0)) \n- \n(sum(rate(image_builder_worker_total_jobs{type=\"depsolve\", status=\"5xx\"}[$interval])) OR on() vector(0))",
     "legendFormat": "success/sec"
    },
    {
     "expr": "(sum(rate(image_builder_worker_total_jobs{type=\"depsolve\", status=\"5xx\"}[$interval])) OR on() vector(0))",
     "legendFormat": "errors/sec"
    }
   ]
  },
  {
   "title": "Depsolve Job Error Rate",
   "type": "timeseries",
   "description": "The number of depsolve job errors (as a percentage) over time for the selected time range",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(image_builder_worker_total_jobs{type=\"depsolve\", status=\"5xx\"}[$interval]))\n  / \n  sum(rate(image_builder_worker_total_jobs{type=\"depsolve\", status!=\"4xx\"}[$interval]))\n)\nOR on() vector(0) # set fallback incase the above query result is empty"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "stat",
   "description": "How long will it take to consume all our budget if our error consumption remains at the current rate for the selected date range.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "28 * 24 * (1 - $stability_slo) \n/ \n(\n  (\n    sum(rate(image_builder_worker_total_jobs{type=\"depsolve\", status=\"5xx\"}[28d]))\n    / \n    sum(rate(image_builder_worker_total_jobs{type=\"depsolve\", status!=\"4xx\"}[28d]))\n  ) OR on() vector(0.01) # set fallback incase the above query result is empty\n)"
    }
   ]
  },
  {
   "title": "Error Budget Consumed",
   "type": "timeseries",
   "description": "The percentage of error budget consumed for the selected time range. ",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  (\n    1 - $stability_slo - (\n      ( \n        sum(increase(image_builder_worker_total_jobs{type=\"depsolve\", status=\"5xx\"}[28d]))\n        /\n        sum(increase(image_builder_worker_total_jobs{type=\"depsolve\", status!=\"4xx\"}[28d]))\n      ) OR on() vector(0)\n    )\n  )\n)\n/ \n(1 - $stability_slo)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  { "title": "Depsolve Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Depsolve Job Duration",
   "type": "stat",
   "description": "The duration of 95% of depsolve jobs",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(image_builder_worker_job_duration_seconds_bucket{type=\"depsolve\"}[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Depsolve Job Duration",
   "type": "timeseries",
   "description": "The request Duration for depsolve jobs over the selected date range",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(image_builder_worker_job_duration_seconds_bucket{type=\"depsolve\"}[$interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(image_builder_worker_job_duration_seconds_bucket{type=\"depsolve\"}[$interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(image_builder_worker_job_duration_seconds_bucket{type=\"depsolve\"}[$interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Slow Request Rate",
   "type": "timeseries",
   "description": "Percent of requests exceeding Duration allowed by SLO",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(rate(image_builder_worker_job_duration_seconds_bucket{le=\"32\", type=\"depsolve\"}[$interval]))/sum(rate(image_builder_worker_job_duration_seconds_count{type=\"depsolve\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "stat",
   "description": "How long will it take to consume all our budget if our error consumption remains at the current rate for the selected date range.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "28 * 24 * (1 - $latency_slo) \n/ \n(\n  1.001 - (\n    (\n      sum(rate(image_builder_worker_job_duration_seconds_bucket{le=\"32\",type=\"depsolve\"}[$__range]))\n      /\n      sum(rate(image_builder_worker_job_duration_seconds_count{type=\"depsolve\"}[$__range]))\n    ) OR on() vector(1) # set fallback incase the above query result is empty\n  )\n)"
    }
   ]
  },
  {
   "title": "Error Budget Consumed",
   "type": "timeseries",
   "description": "The percentage of error budget consumed for the selected time range. ",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  (\n    (\n      sum(increase(image_builder_worker_job_duration_seconds_bucket{le=\"32\", type=\"depsolve\"}[28d]))\n      /\n      sum(increase(image_builder_worker_job_duration_seconds_count{type=\"depsolve\"}[28d])) \n    ) OR on() vector(1)\n  ) - $latency_slo\n)\n/ (1 - $latency_slo)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  { "title": "Job Wait Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Job Wait Duration",
   "type": "stat",
   "description": "The duration of 95% of jobs waiting for execution in the job queue",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(image_builder_worker_job_wait_duration_seconds_bucket[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "Job Wait Duration",
   "type": "timeseries",
   "description": "The  duration for jobs waiting in the job queue over the selected date range",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(image_builder_worker_job_wait_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(image_builder_worker_job_wait_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(image_builder_worker_job_wait_duration_seconds_bucket[$interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Slow Request Rate",
   "type": "timeseries",
   "description": "Percent of requests exceeding duration allowed by SLO",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(rate(image_builder_worker_job_wait_duration_seconds_bucket{le=\"1536\"}[$interval]))/sum(rate(image_builder_worker_job_wait_duration_seconds_count[$interval]))"
    }
   ]
  }
 ]
}