{
 "title": "Image Builder Worker API",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "tenant",
    "query": "crc stage : org-15877963,fedora stage : org-15842261,brew stage : org-16133643,crc production : org-15885990,fedora production : org-16057323,brew production : org-16135456"
   },
   { "name": "stability_slo", "query": "0.95" },
   { "name": "latency_slo", "query": "0.95" }
  ]
 },
 "panels": [
  { "title": "SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "request error budget remaining",
   "type": "stat",
   "description": "How long will it take to consume all our budget if our error consumption remains at the current rate for the selected date range.",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "28 * 24 * (1 - $stability_slo)\n/\n(\n  (\n    sum(rate(image_builder_worker_request_count{code=~\"5.*\", tenant=~\"$tenant\"}[28d]))\n    / \n    sum(rate(image_builder_worker_request_count{code!~\"5.*\", tenant=~\"$tenant\"}[28d]))\n  ) OR on() vector(0.01)\n)"
    }
   ]
  },
  {
   "title": "latency error budget remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "28 * 24 * (1 - $latency_slo) \n/\n(\n  1.001 - (\n    (\n      # the request on the /jobs endpoint lasts 10 seconds, as it's blocking.\n      sum(rate(image_builder_worker_http_duration_seconds_bucket{path!=\"/api/image-builder-worker/v1/jobs\",le=\"0.2\", tenant=~\"$tenant\"}[28d]))\n      /\n      sum(rate(image_builder_worker_http_duration_seconds_count{path!=\"/api/image-builder-worker/v1/jobs\",tenant=~\"$tenant\"}[28d]))\n    ) OR on() vector(1) # set fallback incase the above query result is empty\n  ) \n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request error budget consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  (\n    1 - $stability_slo - (\n      (\n        sum(increase(image_builder_worker_request_count{code=~\"5.*\", tenant=~\"$tenant\"}[28d]))\n        /\n        sum(increase(image_builder_worker_request_count{code!~\"5.*\", tenant=~\"$tenant\"}[28d]))\n      ) OR on() vector(0) # set fallback for empty query result\n    )\n  )\n)\n/\n(1 - $stability_slo)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "latency error budget consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  (\n    (\n      # the request on the /jobs endpoint lasts 10 seconds, as it's blocking.\n      sum(increase(image_builder_worker_http_duration_seconds_bucket{path!=\"/api/image-builder-worker/v1/jobs\",le=\"0.2\",tenant=~\"$tenant\"}[28d]))\n      /\n      sum(increase(image_builder_worker_http_duration_seconds_count{path!=\"/api/image-builder-worker/v1/jobs\",tenant=~\"$tenant\"}[28d]))\n    ) OR on() vector(1)\n  ) - $latency_slo\n)\n/ \n(1 - $latency_slo)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "request throughput",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (path) (rate(image_builder_worker_request_count{code!~\"5.*\", tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{path}} successes/sec"
    },
    {
     "expr": "sum by(path) (rate(image_builder_worker_request_count{code=~\"5.*\", tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "{{path}} errors/sec"
    }
   ]
  },
  { "title": "API latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "request latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(image_builder_worker_http_duration_seconds_bucket{path!=\"/api/image-builder-worker/v1/jobs\",tenant=~\"$tenant\"}[$__range])) by (le)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(image_builder_worker_http_duration_seconds_bucket{path!=\"/api/image-builder-worker/v1/jobs\",tenant=~\"$tenant\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(image_builder_worker_http_duration_seconds_bucket{path!=\"/api/image-builder-worker/v1/jobs\",tenant=~\"$tenant\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(image_builder_worker_http_duration_seconds_bucket{path!=\"/api/image-builder-worker/v1/jobs\",tenant=~\"$tenant\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "slow request rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(rate(image_builder_worker_http_duration_seconds_bucket{le=\"0.2\",path!=\"/api/image-builder-worker/v1/jobs\",tenant=~\"$tenant\"}[$__rate_interval]))/sum(rate(image_builder_worker_http_duration_seconds_count{path!=\"/api/image-builder-worker/v1/jobs\",tenant=~\"$tenant\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request latency",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path) (rate(image_builder_worker_http_duration_seconds_bucket{path!=\"/api/image-builder-worker/v1/jobs\",tenant=~\"$tenant\"}[$__rate_interval]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}