---

- hosts: localhost
  vars:
    passed_tests: []
    failed_tests: []
  vars_files:
    - vars.yml
  tasks:

    - name: Run osbuild-composer base tests
      include_tasks: test_runner_base.yml
      loop: "{{ osbuild_composer_base_tests }}"
      loop_control:
        loop_var: test
      when:
        - test_type == 'base'

    - name: Run osbuild-composer image tests
      include_tasks: test_runner_image.yml
      vars:
        test_cases: "{{ osbuild_composer_image_test_cases }}"
        timeout: "{{ osbuild_composer_image_timeout }}"
        env_vars: "{{ osbuild_composer_image_env_vars }}"
      when:
        - test_type == 'image'

    - name: Run osbuild-composer AWS tests
      include_tasks: test_runner_image.yml
      vars:
        test_cases: "{{ osbuild_composer_aws_test_cases }}"
        timeout: "{{ osbuild_composer_aws_timeout }}"
        env_vars: "{{ osbuild_composer_aws_env_vars }}"
      when:
        - test_type == 'aws'

    - name: Show failed and passed tests
      debug:
        msg: |
          Passed tests: {{ 'None' if not passed_tests else '' }}
          {% for test_name in passed_tests %}
            - {{ test_name }}
          {% endfor %}
          Failed tests: {{ 'None' if not failed_tests else '' }}
          {% for test_name in failed_tests %}
            - {{ test_name }}
          {% endfor %}

    - name: Fail the test run if a test failed
      fail:
        msg: One or more tests failed.
      when: failed_tests