---

- name: Copy worker initialization service
  copy:
    src: "{{ playbook_dir }}/roles/common/files/worker-initialization.service"
    dest: /etc/systemd/system/

- name: Enable worker initialization service
  systemd:
    name: worker-initialization.service
    enabled: yes
    daemon_reload: yes # make sure the new service is loaded before enabling it

- name: Create a directory for initialization scripts
  file:
    path: /usr/local/libexec/worker-initialization-scripts
    state: directory

- name: Copy scripts used by the initialization service
  copy:
    src: "{{ item }}"
    dest: /usr/local/libexec/worker-initialization-scripts
    mode: preserve
  with_fileglob:
    - "{{ playbook_dir }}/roles/common/files/worker-initialization-scripts/*"

