// Package ComposerKoji provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package ComposerKoji

import (
	"context"
	"fmt"
	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/go-chi/chi"
	"net/http"
)

// ComposeRequest defines model for ComposeRequest.
type ComposeRequest struct {
	Distribution  string         `json:"distribution"`
	ImageRequests []ImageRequest `json:"image_requests"`
	Koji          Koji           `json:"koji"`
}

// ComposeResponse defines model for ComposeResponse.
type ComposeResponse struct {
	Id string `json:"id"`
}

// ComposeStatus defines model for ComposeStatus.
type ComposeStatus struct {
	ImageStatuses []ImageStatus `json:"image_statuses"`
	KojiTaskId    int           `json:"koji_task_id"`
	Status        string        `json:"status"`
}

// ImageRequest defines model for ImageRequest.
type ImageRequest struct {
	Architecture string       `json:"architecture"`
	ImageType    string       `json:"image_type"`
	Repositories []Repository `json:"repositories"`
}

// ImageStatus defines model for ImageStatus.
type ImageStatus struct {
	Status string `json:"status"`
}

// Koji defines model for Koji.
type Koji struct {
	Server string `json:"server"`
}

// Repository defines model for Repository.
type Repository struct {
	Baseurl string `json:"baseurl"`
}

// PostComposeJSONBody defines parameters for PostCompose.
type PostComposeJSONBody ComposeRequest

// PostComposeRequestBody defines body for PostCompose for application/json ContentType.
type PostComposeJSONRequestBody PostComposeJSONBody

type ServerInterface interface {
	// Create compose (POST /compose)
	PostCompose(w http.ResponseWriter, r *http.Request)
	// The status of a compose (GET /compose/{id})
	GetComposeId(w http.ResponseWriter, r *http.Request)
}

// PostCompose operation middleware
func PostComposeCtx(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// GetComposeId operation middleware
func GetComposeIdCtx(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		var err error

		// ------------- Path parameter "id" -------------
		var id string

		err = runtime.BindStyledParameter("simple", false, "id", chi.URLParam(r, "id"), &id)
		if err != nil {
			http.Error(w, fmt.Sprintf("Invalid format for parameter id: %s", err), http.StatusBadRequest)
			return
		}

		ctx = context.WithValue(ctx, "id", id)

		next.ServeHTTP(w, r.WithContext(ctx))
	})
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerFromMux(si, chi.NewRouter())
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	r.Group(func(r chi.Router) {
		r.Use(PostComposeCtx)
		r.Post("/compose", si.PostCompose)
	})
	r.Group(func(r chi.Router) {
		r.Use(GetComposeIdCtx)
		r.Get("/compose/{id}", si.GetComposeId)
	})

	return r
}

