---
name: "Updates Go dependencies via gobump"

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    # Every Monday at 6:00 PM (one hour after images release)
    - cron: "0 6 * * 1"

jobs:
  update-and-push:
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:43
    steps:
      - name: Prepare environment and run tests
        run: |
          set -xe
          sudo dnf -y install git gh jq golang skopeo libvirt-devel gpgme-devel btrfs-progs-devel krb5-devel
          git clone --depth 1 https://github.com/osbuild/osbuild-composer
          cd osbuild-composer/
          make build test

      - name: Run gobump and open a PR
        env:
          GH_TOKEN: ${{ secrets.SCHUTZBOT_GITHUB_ACCESS_TOKEN }}
        run: |
          set -xe
          cd osbuild-composer/
          git config user.name "schutzbot"
          git config user.email "schutzbot@gmail.com"
          branch="schutz-gobump-$(date -I)"
          git checkout -b "${branch}"
          go run github.com/lzap/gobump@latest \
            -exec "./tools/prepare-source.sh" \
            -exec "make build test" \
            -verbose -format markdown | tee "/tmp/github_pr_body.txt"

          # Check and update spec file version if needed
          REQUIRED_VERSION=$(cat vendor/github.com/osbuild/image-builder/data/dependencies/osbuild | tr -d '[:space:]')
          CURRENT_VERSION=$(grep '^%global min_osbuild_version' osbuild-composer.spec | awk '{print $3}')
          if [ "${CURRENT_VERSION}" != "${REQUIRED_VERSION}" ]; then
            sed -i "s/^%global min_osbuild_version .*/%global min_osbuild_version ${REQUIRED_VERSION}/" osbuild-composer.spec
            git add osbuild-composer.spec
            git commit -m "chore: update spec with new images minimum version"
          else
            echo "Spec file version is already up to date (${CURRENT_VERSION})"
          fi

          git log --oneline "main..${branch}"
          git push -f "https://$GH_TOKEN@github.com/schutzbot/osbuild-composer.git" "${branch}"
          gh pr create \
            -t "Update dependencies $(date -I)" \
            -F "/tmp/github_pr_body.txt" \
            --repo "osbuild/osbuild-composer" \
            --base "main" \
            --head "schutzbot:${branch}"
